# Dockerfile.migrations
# esta versión de node tiene soporte para arquitecturas ARM
FROM node:16-bullseye
WORKDIR /opt/app
COPY ./db/migrations ./db/migrations
COPY ./knexfile.js ./knexfile.js
# Añadimos el wait-for-it y le damos permisos de ejecución
COPY ./wait-for-it.sh ./wait-for-it.sh
RUN chmod +x wait-for-it.sh
RUN npm init -y
RUN npm install knex pg dotenv