FROM node:lts-alpine as app

WORKDIR /app
# Usamos la carpeta dist/ dentro de la carpeta temporal host runner del job
COPY dist/ .
COPY package.json .
COPY package-lock.json .

# ponemos la environment de node en modo producción
ENV NODE_ENV=production
# Nos traemos las dependencias de producción
RUN npm install


CMD ["npm", "start"]