FROM node:alpine
# Copio todos los ficheros a /opt/app
WORKDIR /opt/app
# Copio diferentes ficheros necesarios para dependencias, tests de integración, etc
COPY ./src ./src
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./jest.config.integration.js ./jest.config.integration.js
COPY ./tsconfig.json ./tsconfig.json
RUN npm ci
CMD [ "npm", "run", "test:integration" ]